open_ai_key=""

#Prompt for Sentiment Analysis--------
sentiment_prompt=f"Your role is Business analyst who tries to understand the transcript that generates from recording of a conversations between two or more people and provide response in JSON format.In these transcription people could be interviewer and candidate or loan recovery agent and Detour or from any domain.Carefully Read conversations and share response in given JSON format only. You also include various other things in topic list like whether any foul or bad language used and by whom in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary report and its agregate sentiment.In a key DiscussionSummary You also need to provide action items and their owners.At very top you should provide summary of discussion in 50 to 150 words. Determine the value for JSON key 'Score' will be out of 10 for example 7, 2 or so on.The Foul Language examples are as follows"
sentiment_prompt_after_inject='The conversation text will be available between two @@@. For giving responses follows these JSON key value only in 1) Summary 2).Topics,3)FoulLanguage 4)ActionItems 5)ActionOwners 6)Score 7)AggregateSentiment 8)Compliance Score and 9)Good bye reminder message and date also.for JSON key Topics you will return subset in the format as follows "Topic": "<Topic Name>","Sentiment": "<Positive/Negative/Neutral>","FoulLanguage": "<Yes/NO>" ,"ActionItems": ["<List of Action items for the topic>"],"ActionOwners": ["<Owner of actions>"],"Score": "<Sentiment Score out of 10>".Be careful about future and past date and time predictions as they are associate about future actions items. For example if reminder is for after a month then you need to generate required date as SUM of Date Mentioned in transcription Plus 1 month and if it is for 1 week then it would be date discussed in transcription Plus 1 week. Transcribe text starts as follows '
# after_prohibited_prompt=f'The conversation text will be available between two @@@. For giving responses follows these JSON key value only in 1) Summary 2).Topics,3)FoulLanguage 4)ActionItems 5)ActionOwners 6)Score 7)AggregateSentiment 8)Compliance Score and 9)Good bye reminder message and date also.for JSON key Topics you will return subset in the format as follows "Topic": "<Topic Name>","Sentiment": "<Positive/Negative/Neutral>","FoulLanguage": "<Yes/NO>" ,"ActionItems": ["<List of Action items for the topic>"],"ActionOwners": ["<Owner of actions>"],"Score": "<Sentiment Score out of 10>".Be careful about future and past date and time predictions as they are associate about future actions items. For example if reminder is for after a month then you need to generate required date as SUM of Date Mentioned in transcription Plus 1 month and if it is for 1 week then it would be date discussed in transcription Plus 1 week. Transcribe text starts as follows @@@'

#prompt for Both Sentiment and Compliance---
prompt_for_data_key_never_blank="Make sure that action or OverallScore item will not contain any blank values. Blank value will only be considered in exceptional cases."
#---End---------

#Prompt for Compliance Analysis--------

compliance_prompt="As a Business Analyst, your role involves analyzing transcripts generated from recordings of conversations between two or more individuals and providing responses in JSON format. These conversations could involve various scenarios such as loan recovery negotiations,debt collection.Always remember that Debt collection is the process by which a collector pursues the repayment of outstanding debts owed by individuals or businesses. This typically involves contacting debtors, negotiating payment arrangements, and potentially employing legal means to recover funds owed. The aim is to ensure that creditors receive the money owed to them while adhering to relevant laws and regulations governing debt collection practices.Your task is to carefully read the conversations, identify key points, and structure the response in the specified JSON format.Here is the compliance available between two ### as follows ###"
compliance_prompt_after_checklist='###.Return the data as given the dictionary {"identification_of_agent": {"compliance_met": ,"details": ""},"call_monitoring_notification": {"compliance_met": ,"details": ""},"debtor_identification": {"compliance_met": ,"details": ""},"alternative_identity_verification": {"compliance_met": ,"details": },"organization_introduction": {"compliance_met": ,"details": ""},"original_financial_institution": {"compliance_met": ,"details": ""},"balance_information": {"compliance_met": ,"details": ""},"avoidance_of_negative_statements": {"compliance_met": ,"details": ""},"professional_tone_and_active_listening": {"compliance_met": ,"details": ""},"next_step_information": {"compliance_met": ,"details": ""},"OverallScore": ""}. The "next_step_information" key changed to "closure_of_call" and compliance_met key value always return in true/false.'


