prompt_text="Please read the conversations and shares a list of topics in JSON format along with topic you also provide the sentiment analysis reports with every discussed topic. You also include various other things in topic list like whether any foul or bad language used in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary and its agregate sentiment. The conversation will be available between two @@@ as follows @@@"

prompt1="Your role is Business analyst who tries to understand the transcript that generates from recording of a conversations between two or more people.These people could be interviewer and candidate or loan recovery agent and Detour.Please read the conversations and shares a list of topics in dictionary key value format along with topic you also provide the sentiment analysis reports with every discussed topic. You also include various other things in topic list like whether any foul or bad language used and by whom in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary report and its agregate sentiment.You also need to provide action items and their owners.At very top you should provide summary of discussion with dictionary key value topicSummary all discussed topics in 50 to 150 words.The conversation will be available between two @@@ as follows @@@"



prompt3="Please read the conversation carefully who reads conversations between sender and receiver Please read the conversations and shares a list of topics in dictionary key value format along with topic you also provide the sentiment analysis reports with every discussed topic. You also include various other things in topic list like whether any foul or bad language used and by whom in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary report and its agregate sentiment.You also need to provide action items and associates owners.At very top you should provide summary of discussion with dictionary key value topicSummary all discussed topics in 50 to 150 words.The conversation will be available between two @@@ as follows @@@"
prompt5="Please read the conversation carefully who reads conversations between sender and receiver Please read the conversations and shares a list of topics in dictionary key value format along with topic you also provide the sentiment analysis reports with every discussed topic. You also include various other things in topic list like whether any foul or bad language used and by whom in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary report and its agregate sentiment.You also need to provide action items and associates owners.At very top you should provide summary of discussion with dictionary key value topicSummary all discussed topics in 50 to 150 words.The conversation will be available between two @@@ as follows @@@"
prompt4="Please read the conversation carefully who reads conversations between Agent and Detour Please read the conversations and shares a list of topics in dictionary key value format along with topic you also provide the sentiment analysis reports with every discussed topic. You also include various other things in topic list like whether any foul or bad language used and by whom in discussion,You can also add various other things in the list and share the socre and one final agregate socre of this summary report and its agregate sentiment.You also need to provide action items and associates Agent-Detour.At very top you should provide summary of discussion with dictionary key value topicSummary all discussed topics in 50 to 150 words.The conversation will be available between two @@@ as follows @@@"

prepare_prompt=""
open_ai_key=""
open_ai_key_sanjeev=""