class CONSTANT:
    STATUS_RECORDING = 'Recording',
    STATUS_PROCESSING = 'Processing'
    STATUS_COMPLETED = 'CompletedTranscript'
    STATUS_FAILED = 'Failed'
    STATUS_DRAFT = 'Draft'
    STATUS_EXPORTED = 'Exported'
    AUTHENTICATION_OAUTH = 'OAuth'
    AUTHENTICATION_LDAP = 'LDAP'
    SUBSCRIPTION_TYPE_SMALL ='Small'
    SUBSCRIPTION_TYPE_NORMAL = 'Normal'
    SUBSCRIPTION_TYPE_PREMIUM = 'Premium'
    WHISPER_MODEL_BASIC = 'Basic'
    WHISPER_MODEL_TINY = 'TINY'

